apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "video-app.fullname" . }}-restarter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "video-app.fullname" . }}-restarter
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "video-app.fullname" . }}-restarter
subjects:
- kind: ServiceAccount
  name: {{ include "video-app.fullname" . }}-restarter
roleRef:
  kind: Role
  name: {{ include "video-app.fullname" . }}-restarter
  apiGroup: rbac.authorization.k8s.io